# Generated by Django 4.0 on 2022-01-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('birthday', models.DateField()),
                ('placeOfBirth', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
