# Generated by Django 4.0 on 2022-01-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_email_profile_name_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isAnswered',
            field=models.BooleanField(default=False),
        ),
    ]
